CREATE DATABASE IF NOT EXISTS BANCO1;

USE BANCO1;

CREATE TABLE IF NOT EXISTS users2 (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) unique NOT NULL,
    telefone VARCHAR(100) unique NOT NULL,
    email VARCHAR(100) unique NOT NULL,
    senha VARCHAR(100) NOT NULL,

    criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS produto (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(100) unique NOT NULL,
    descricao VARCHAR(100) NOT NULL,
    quantidade int,
    preco DECIMAL(10, 2) NOT NULL,

    criado TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);